// 18
var places = ["Pakistan", "Malaysia", "Canada", "Turki", "Saudia"];
console.log(places);
var places = ["Pakistan", "Malaysia", "Canada", "Turki", "Saudia"];
var stored = places.sort();
console.log(stored);
var places = ["Pakistan", "Malaysia", "Canada", "Turki", "Saudia"];
console.log(places);
var places = ["Pakistan", "Malaysia", "Canada", "Turki", "Saudia"];
var stored = places.reverse();
console.log(stored);
var places = ["Pakistan", "Malaysia", "Canada", "Turki", "Saudia"];
console.log(places);
// var places = ["Pakistan","Malaysia","Canada", "Turki", "Saudia"];  
// var stored = places.toString();
// console.log(stored);
var places = ["Pakistan", "Malaysia", "Canada", "Turki", "Saudia"];
var stored = places.reverse();
console.log(stored, ", The order of the list has been reversed.");
var places = ["Pakistan", "Malaysia", "Canada", "Turki", "Saudia"];
var stored = places;
console.log(stored, ", The order of the list has been changed again.");
var places = ["Pakistan", "Malaysia", "Canada", "Turki", "Saudia"];
var stored = places.sort();
console.log(stored, ", The order of the list has been sorted alphabaticaly.");
